#conda env create -f environment.yaml
#conda activate web_homework_microservice

name: web_homework_microservice
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.2
  - pip
  - peewee
  - starlette
  - pydantic
  - pip:
    - fastapi[standard]
    - uvicorn